service: aws-lambda-sample

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-webpack

functions:
  fetchTweets:
    handler: handler.fetchTweets

    events:
     - http:
         path: tweets
         method: get
